✨ Feature - 관리자 api 생성
Ownsaemiro/ownsaemiro-server pull request #11
Opened 2024-06-02 09:15 UTC by dlawjddn

## Issue
You need to link it to the index specifying which issue you addressed.

- Resolves : 
 
## What To Do
You should present a list of what you've done in the corresponding pull request.

- 관리자 api 생성
- 이거 역시 많아질 듯 해서 미리 올림

2024-06-02 17:15 UTC, kurtyoon requested changes
코멘트 확인해주세요

2024-06-02 17:15 UTC, kurtyoon commented on src/main/java/org/dongguk/ownsaemiro/ownsaemiroserver/controller/AdminController.java
> +        AdminApplyEventDto adminApplyEventDto = eventService.showAppliesOfSeller(page-1, size);
이거 page 0으로 들어오면 에러 안터지나요?

2024-06-02 17:15 UTC, kurtyoon commented on src/main/java/org/dongguk/ownsaemiro/ownsaemiroserver/controller/AdminController.java
> +        AdminApplyEventDto adminApplyEventDto = eventService.searchEventRequest(name, state, page-1, size);
여기도요

2024-06-02 17:15 UTC, kurtyoon commented on src/main/java/org/dongguk/ownsaemiro/ownsaemiroserver/domain/Event.java
> +    @Transactional
도메인단에 트랜잭션을 거는 것 보다는, 해당 함수를 서비스 단에서 호출하고, 해당 서비스에 트랜잭션 거는게 더 좋아 보입니다

2024-06-03 02:27 UTC, dlawjddn commented on src/main/java/org/dongguk/ownsaemiro/ownsaemiroserver/domain/Event.java
> +    @Transactional
바로 밑 커밋에 반영 완료~!

2024-06-03 02:27 UTC, dlawjddn commented on src/main/java/org/dongguk/ownsaemiro/ownsaemiroserver/controller/AdminController.java
> +        AdminApplyEventDto adminApplyEventDto = eventService.searchEventRequest(name, state, page-1, size);
바로 밑 커밋에 반영 완료~!

2024-06-03 04:23 UTC, kurtyoon approved these changes
고생하셨습니당

2024-06-03 04:55 UTC, merged