✨ Feature - 판매자 api 생성 완료
Ownsaemiro/ownsaemiro-server pull request #9
Opened 2024-05-31 19:42 UTC by dlawjddn

## Issue
You need to link it to the index specifying which issue you addressed.

- Resolves : #8 
 
## What To Do
You should present a list of what you've done in the corresponding pull request.

- 아직 다 안했는데 한번에 올리면 양이 너무 많아질거 같아서 미리 올리고 업데이트 하겠음!

2024-06-01 05:23 UTC, kurtyoon requested changes
코멘트 확인해주세요!

2024-06-01 05:23 UTC, kurtyoon commented on src/main/java/org/dongguk/ownsaemiro/ownsaemiroserver/controller/SellerController.java
> +    public ResponseDto<?> showApplies(@UserId Long userId, @RequestParam("page") Integer page, @RequestParam("size") Integer size){
defaultValue 필요합니다. 보통은 page=0, size=10으로 둡니다!

2024-06-01 05:23 UTC, kurtyoon commented on src/main/java/org/dongguk/ownsaemiro/ownsaemiroserver/controller/SellerController.java
> +            @RequestParam("size") Integer size){
위와 마찬가지 입니다.

2024-06-01 16:11 UTC, dlawjddn commented on src/main/java/org/dongguk/ownsaemiro/ownsaemiroserver/controller/SellerController.java
> +    public ResponseDto<?> showApplies(@UserId Long userId, @RequestParam("page") Integer page, @RequestParam("size") Integer size){
넹!

2024-06-01 16:11 UTC, dlawjddn commented on src/main/java/org/dongguk/ownsaemiro/ownsaemiroserver/controller/SellerController.java
> +            @RequestParam("size") Integer size){
넹!

2024-06-02 03:53 UTC, kurtyoon approved these changes
코멘트 확인해주시고, 확인하셨으면 병합해주세요!

2024-06-02 03:53 UTC, kurtyoon commented on src/main/java/org/dongguk/ownsaemiro/ownsaemiroserver/service/EventService.java
> +    private static String convertDate(LocalDate date){
이런 자주쓰는 함수들은 따로 클래스를 빼서 정적으로 관리하는게 메모리 관리 차원에서는 효율적입니다!

2024-06-02 05:42 UTC, merged